# Generated by Django 3.2 on 2021-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
                ('para1', models.TextField(max_length=300)),
                ('para2', models.TextField(max_length=300)),
            ],
        ),
    ]
